services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    networks:
      - app-network
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge